using Avalonia.Media;

namespace CM_Simulator.ViewModels;

/// <summary>
/// The state every LVICC page (ICC1ViewModel .. ICC21ViewModel) exposes to the
/// rest of the app. All of these are generated by [ObservableProperty] on the
/// page view models; the interface just lets callers work with any page by number
/// instead of repeating the same code 21 times.
/// </summary>
public interface ILviccPage
{
    // LVICC SWITCH
    IBrush OffButton { get; set; }
    IBrush OffForeground { get; set; }
    IBrush RemButton { get; set; }
    IBrush RemForeground { get; set; }
    IBrush LowButton { get; set; }
    IBrush LowForeground { get; set; }
    IBrush MedButton { get; set; }
    IBrush MedForeground { get; set; }
    IBrush HighButton { get; set; }
    IBrush HighForeground { get; set; }

    // CONFIGURATION
    IBrush FlashHeadBackground { get; set; }
    IBrush MtBackground { get; set; }
    IBrush ModeBackground { get; set; }
    IBrush ControlBackground { get; set; }
    IBrush ElevatedBackground { get; set; }
    IBrush InPavementBackground { get; set; }
    IBrush CompatBackground { get; set; }
    IBrush EnhancedBackground { get; set; }
    string ModeStatus { get; set; }
    string ControlType { get; set; }

    // LVICC short data fields
    string Vac240V { get; set; }
    string Vac240A { get; set; }
    string Vdc33V { get; set; }
    string Vdc5V { get; set; }
    string Vdc8V { get; set; }
    string Vdc8A { get; set; }
    string Vdc18V { get; set; }
    string TriggerPulseWidth { get; set; }
    string TriggerPulseDelay { get; set; }
    string TriggerPeriod { get; set; }
    string TriggerCurrent { get; set; }
    string AnodePulseWidth { get; set; }
    string AnodePulseDelay { get; set; }
    string BleederV { get; set; }
    string FlasherMisfires { get; set; }

    // PLCK short data fields
    string PlckVdc33V { get; set; }
    string PlckVdc5V { get; set; }
    string PlckVdc8V { get; set; }
    string PlckCpuTemp { get; set; }
    string PlckPercentBusy { get; set; }
    string PlckMaxPercentBusy { get; set; }

    // Error indicators
    bool IsCommandErrorVisible { get; set; }
    bool IsMisfireErrorVisible { get; set; }
    bool IsCommErrorVisible { get; set; }
    bool IsModeErrorVisible { get; set; }
}
