using Avalonia.Media;

namespace CM_Simulator.ViewModels;

/// <summary>
/// The state every LVICC page (ICC1ViewModel .. ICC21ViewModel) exposes to the
/// rest of the app. All of these are generated by [ObservableProperty] on the
/// page view models; the interface just lets callers work with any page by number
/// instead of repeating the same code 21 times.
/// </summary>
public interface ILviccPage
{
    // LVICC SWITCH
    IBrush OffButton { get; set; }
    IBrush OffForeground { get; set; }
    IBrush RemButton { get; set; }
    IBrush RemForeground { get; set; }
    IBrush LowButton { get; set; }
    IBrush LowForeground { get; set; }
    IBrush MedButton { get; set; }
    IBrush MedForeground { get; set; }
    IBrush HighButton { get; set; }
    IBrush HighForeground { get; set; }

    // CONFIGURATION
    IBrush FlashHeadBackground { get; set; }
    IBrush MtBackground { get; set; }
    IBrush ModeBackground { get; set; }
    IBrush ControlBackground { get; set; }
    IBrush ElevatedBackground { get; set; }
    IBrush InPavementBackground { get; set; }
    IBrush CompatBackground { get; set; }
    IBrush EnhancedBackground { get; set; }
    string ModeStatus { get; set; }
    string ControlType { get; set; }

    // Error indicators
    bool IsCommandErrorVisible { get; set; }
    bool IsMisfireErrorVisible { get; set; }
    bool IsCommErrorVisible { get; set; }
    bool IsModeErrorVisible { get; set; }
}
